version: '3'

services:
  nestjs-app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgre
      - DB_NAME=disk
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgre
      - POSTGRES_DB=disk